spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size : 1000

  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
