spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/studyolle
    username: seongje
    password: 52ajrdjdy

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size : 1000